export class UpdateJobSeekerDTO{
    jobSeekerId : number;
    jobSeekerName : string;
    userName : string;
    email : string;
    password : string;
    gender : string;
    contactPhone : string;
    address : string;
    description : string;
    dateOfBirth : Date;
    qualification : string;
    specialization : string;
    institute : string;
    year : number;
    cgpa : number;
    companyName : string;
    position : string;
    responsibilities : string;
    startDate : Date;
    endDate : Date;
}